# Generated by Django 4.2.4 on 2023-09-12 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=15)),
                ('tipo_documento', models.CharField(blank=True, choices=[('Sin Informacion', 'Sin Informacion'), ('Tarjeta de Identidad', 'Tarjeta de Identidad'), ('Cédula de Ciudadanía', 'Cédula de Ciudadanía'), ('Cédula de Extranjería', 'Cédula de Extranjería'), ('Registro Civil de Nacimiento', 'Registro Civil de Nacimiento'), ('Permiso Especial de Permanencia', 'Permiso Especial de Permanencia')], default='Sin Informacion', max_length=40, null=True)),
                ('documento', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
